# Generated by Django 2.2 on 2024-06-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20240627_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='movimento',
            field=models.CharField(blank=True, choices=[('e', 'entrada'), ('s', 'saida')], max_length=1),
        ),
    ]
